Annotation workflow refactor
NBISweden/pipelines-nextflow pull request #75
Opened 2022-07-13 12:14 UTC by mahesh-panchal

Closes #71 

Refactors the repository to fit nf-core stylings.

2022-08-12 12:15 UTC, verku requested changes
Hi!

Great work with the updates and putting all pipelines together! I'm focusing on the README's at this point.

In the main README.md it would be helpful if you could add a short introductory section explaining that this is a Nextflow pipeline with several subworkflows that run different steps of a genome annotation project. It might also be helpful to move the last section "Available pipelines" to this introduction. I would move "See their respective READMEs for operation instructions." to the "general usage" section and merge the sentence with "See the workflow specific README's for workflow parameter details."

The section "General usage" does not mention that there already is a workflow config file called "nextflow.config" that can (should be?) used. Also, can you clarify at some point that only the annotation preprocessing and the transcript assembly pipelines can be run simultaneously (unless the pipeline is written so that only one subworkflow can be run at once, this is not clear to me), but ab initio training and functional annotation require input from different MAKER runs. Maybe it could be a good idea to describe a general annotation project in the README.md file highlighting at which points the Nextflow pipelines can be run. 

The README's for each subworkflow all differ from the README.md in the command to run each subworkflow which is confusing. Is it `nextflow run NBISweden/pipelines-nextflow ...` or `nextflow run main.nf`? The latter command probably has to be run from standing within the subworkflows directory? Can you clarify this in the README's?

The first sentence in "Tool specific parameters" is hard to understand for people with no/limited programming background: "Process specific options are passed by overriding the ext.args variable using a process selector in a configuration file." It might be a bit easier to understand if you wrote "Additional tool specific parameters are passed by overriding the ext.args variable for the respective process in a configuration file". 

I hope this helps!

2022-08-15 13:13 UTC, mahesh-panchal commented
Thanks for the feedback @verku . How's this?

2022-08-15 13:44 UTC, verku approved these changes

2022-08-15 13:56 UTC, mahesh-panchal commented
Cannot replicate "Buffer underflow" error. All tests currently pass manually.

2022-08-15 19:05 UTC, LucileSol approved these changes

2022-08-16 11:06 UTC, merged